### ISSUE TITLE
Device frames don't load immediately

### ISSUE THREAD

**Issue by agordeev** [pixelsign/html5-device-mockups#32]
Insteat, they blink in after a small delay. Also, when the page is not active for some time, the same effect occurs.
Browser: Firefox 50.1.0.

**Comment by ben182** [comment]
Hey andrew8712,

I think thats caused by the lazy loading. We do not perload every device when the site loads. We would end up with a lot of traffic. Insted when you change the phone, the browser loads the image. You can test this by switching the same 2 devices. On the first switch, the delay occurs. From the second time on, the devices switch intant.

Ben
